
spring:
  application.name: loans
  datasource:
    url: jdbc:mysql://localhost:3306/accounts-ms-db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    config:
      enabled: false